name: Next.js Build

on:
  push:
    branches:
      - master # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - master # Trigger the workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use Node.js 16 (adjust to your project's Node version)

      - name: Install dependencies
        run: |
          npm install

      - name: Run linting and types validation
        run: |
          npm run lint
          npm run type-check  # Run type-checking if using TypeScript

      - name: Build Next.js app
        run: |
          npm run build
